name: Ci Test1

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
    branches:
      - main
  workflow_dispatch:
  issues:
    types: [opened]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install project
        run: npm install
      - name: run the project build
        run: npm run build
      - name: run the project tests
        run: npm run test
